/**
 * OSCAL export (§19) — a documented SUBSET of NIST OSCAL, not the full standard.
 *
 * We emit an OSCAL-shaped component-definition + assessment-results object that
 * maps model components to selected NIST SP 800-171 controls, with assessment
 * findings derived from the assurance gates and references to evidence. The
 * `_ibe_meta.implemented_fields` / `omitted_fields` make explicit what is and is
 * not populated. THIS IS NOT A CLAIM OF CMMC CERTIFICATION.
 */

import type { Digest } from '../shared/index.js';
import type { GateOutcome } from '../assurance/index.js';

export interface ControlMapping {
  componentId: string;
  controlIds: string[]; // e.g. "3.1.1", "3.13.16"
  status: 'implemented' | 'partial' | 'planned';
  statement: string;
}

export interface OscalExportInput {
  systemName: string;
  modelVersion: string;
  components: Array<{ id: string; name: string; description: string; responsibleRole: string }>;
  controlMappings: ControlMapping[];
  gates: GateOutcome[];
  evidenceRefs: string[];
  decision: 'accepted' | 'refused';
  timestamp: string;
  certificateId: string;
  artifactDigest: Digest;
}

/** NIST SP 800-171 control titles for the subset we reference. */
const CONTROL_TITLES: Record<string, string> = {
  '3.1.1': 'Limit system access to authorized users, processes, and devices.',
  '3.1.3': 'Control the flow of CUI in accordance with approved authorizations.',
  '3.1.20': 'Verify and control connections to external systems.',
  '3.3.1': 'Create and retain system audit logs and records.',
  '3.4.1': 'Establish and maintain baseline configurations.',
  '3.4.3': 'Track, review, approve, and log changes to systems.',
  '3.13.1': 'Monitor and control communications at external boundaries.',
  '3.13.16': 'Protect the confidentiality of CUI at rest.',
  '3.14.6': 'Monitor systems to detect attacks and indicators of potential attacks.',
};

export function exportOscal(input: OscalExportInput): Record<string, unknown> {
  const findings = input.gates.map((g) => ({
    uuid: `finding-${g.id}`,
    title: g.clause,
    target: {
      type: 'objective-id',
      'target-id': g.id,
      status: { state: g.passed ? 'satisfied' : 'not-satisfied' },
    },
    'related-observations': g.reasons.map((r) => ({ 'observation-uuid': `obs-${r.code}` })),
  }));

  const observations = input.gates
    .flatMap((g) => g.reasons.map((r) => ({ gate: g.id, r })))
    .map(({ gate, r }, i) => ({
      uuid: `obs-${gate}-${i}`,
      description: r.message,
      methods: ['TEST'],
      collected: input.timestamp,
    }));

  return {
    _ibe_meta: {
      note: 'OSCAL SUBSET generated by IBE. NOT a CMMC/NIST certification. For assessment-support use only.',
      implemented_fields: [
        'component-definition.components',
        'component-definition.components.control-implementations',
        'assessment-results.results.findings',
        'assessment-results.results.observations',
        'assessment-results.results.reviewed-controls',
        'responsible-roles',
        'evidence references (via back-matter resources)',
        'implementation-status',
        'timestamps',
      ],
      omitted_fields: [
        'ssp (system-security-plan) linkage',
        'profile/catalog resolution',
        'parties/locations full metadata',
        'poam (plan of action & milestones)',
        'digital signatures on the OSCAL doc itself (IBE signs the certificate instead)',
      ],
    },
    'component-definition': {
      uuid: `cd-${input.modelVersion}`,
      metadata: {
        title: `${input.systemName} — IBE component definition`,
        version: input.modelVersion,
        'oscal-version': '1.1.2',
        'last-modified': input.timestamp,
      },
      components: input.components.map((c) => {
        const mappings = input.controlMappings.filter((m) => m.componentId === c.id);
        return {
          uuid: `comp-${c.id}`,
          type: 'software',
          title: c.name,
          description: c.description,
          'responsible-roles': [{ 'role-id': c.responsibleRole, 'party-uuids': [] }],
          'control-implementations': [
            {
              uuid: `ci-${c.id}`,
              source: 'NIST_SP-800-171_rev2',
              description: `Controls implemented by ${c.name}`,
              'implemented-requirements': mappings.flatMap((m) =>
                m.controlIds.map((ctrl) => ({
                  uuid: `ir-${c.id}-${ctrl}`,
                  'control-id': ctrl,
                  description: `${CONTROL_TITLES[ctrl] ?? 'control'} — ${m.statement}`,
                  props: [{ name: 'implementation-status', value: m.status }],
                })),
              ),
            },
          ],
        };
      }),
    },
    'assessment-results': {
      uuid: `ar-${input.certificateId}`,
      metadata: {
        title: `${input.systemName} — IBE assessment results`,
        version: input.modelVersion,
        'oscal-version': '1.1.2',
        'last-modified': input.timestamp,
      },
      results: [
        {
          uuid: `result-${input.certificateId}`,
          title: `IBE assurance decision: ${input.decision}`,
          start: input.timestamp,
          'reviewed-controls': {
            'control-selections': [
              {
                'include-controls': [
                  ...new Set(input.controlMappings.flatMap((m) => m.controlIds)),
                ].map((id) => ({ 'control-id': id })),
              },
            ],
          },
          observations,
          findings,
        },
      ],
      'back-matter': {
        resources: input.evidenceRefs.map((ref) => ({
          uuid: `res-${ref}`,
          title: `evidence:${ref}`,
        })),
      },
    },
  };
}
